// Knights Province dynamic script.
// Wiki available at: https://github.com/Kromster80/knights_province/wiki

var
  Camp: Integer;
  stoneInCamp: Integer;

procedure OnMissionStart;
var
  I, K: Integer;
begin
  Camp := States.HouseAt(15,30);
  stoneInCamp := States.HouseWareInside(Camp, wtStone);

  for I := 10 to 19 do
  for K := 34 to 35 do
  begin
    Actions.PlanAddRoad(0, I, K);
    Dec(stoneInCamp);
  end;
end;

procedure OnTick(aTick: Integer);
begin
  if States.HouseWareInside(Camp, wtStone) = stoneInCamp then
    Actions.PlayerWin([0], True);
end;